// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/msg.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type TwoNumRequest struct {
	A                    float32  `protobuf:"fixed32,1,opt,name=a,proto3" json:"a,omitempty"`
	B                    float32  `protobuf:"fixed32,2,opt,name=b,proto3" json:"b,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwoNumRequest) Reset()         { *m = TwoNumRequest{} }
func (m *TwoNumRequest) String() string { return proto.CompactTextString(m) }
func (*TwoNumRequest) ProtoMessage()    {}
func (*TwoNumRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_85aa4552279d3b4a, []int{0}
}

func (m *TwoNumRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoNumRequest.Unmarshal(m, b)
}
func (m *TwoNumRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoNumRequest.Marshal(b, m, deterministic)
}
func (m *TwoNumRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoNumRequest.Merge(m, src)
}
func (m *TwoNumRequest) XXX_Size() int {
	return xxx_messageInfo_TwoNumRequest.Size(m)
}
func (m *TwoNumRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoNumRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TwoNumRequest proto.InternalMessageInfo

func (m *TwoNumRequest) GetA() float32 {
	if m != nil {
		return m.A
	}
	return 0
}

func (m *TwoNumRequest) GetB() float32 {
	if m != nil {
		return m.B
	}
	return 0
}

type TwoNumResponse struct {
	C                    float32  `protobuf:"fixed32,3,opt,name=c,proto3" json:"c,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TwoNumResponse) Reset()         { *m = TwoNumResponse{} }
func (m *TwoNumResponse) String() string { return proto.CompactTextString(m) }
func (*TwoNumResponse) ProtoMessage()    {}
func (*TwoNumResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_85aa4552279d3b4a, []int{1}
}

func (m *TwoNumResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TwoNumResponse.Unmarshal(m, b)
}
func (m *TwoNumResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TwoNumResponse.Marshal(b, m, deterministic)
}
func (m *TwoNumResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TwoNumResponse.Merge(m, src)
}
func (m *TwoNumResponse) XXX_Size() int {
	return xxx_messageInfo_TwoNumResponse.Size(m)
}
func (m *TwoNumResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TwoNumResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TwoNumResponse proto.InternalMessageInfo

func (m *TwoNumResponse) GetC() float32 {
	if m != nil {
		return m.C
	}
	return 0
}

func init() {
	proto.RegisterType((*TwoNumRequest)(nil), "math.TwoNumRequest")
	proto.RegisterType((*TwoNumResponse)(nil), "math.TwoNumResponse")
}

func init() { proto.RegisterFile("proto/msg.proto", fileDescriptor_85aa4552279d3b4a) }

var fileDescriptor_85aa4552279d3b4a = []byte{
	// 172 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0xe2, 0x2f, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0xcf, 0x2d, 0x4e, 0xd7, 0x03, 0xb3, 0x84, 0x58, 0x72, 0x13, 0x4b, 0x32, 0x94, 0xb4,
	0xb9, 0x78, 0x43, 0xca, 0xf3, 0xfd, 0x4a, 0x73, 0x83, 0x52, 0x0b, 0x4b, 0x53, 0x8b, 0x4b, 0x84,
	0x78, 0xb8, 0x18, 0x13, 0x25, 0x18, 0x15, 0x18, 0x35, 0x98, 0x82, 0x18, 0x13, 0x41, 0xbc, 0x24,
	0x09, 0x26, 0x08, 0x2f, 0x49, 0x49, 0x8e, 0x8b, 0x0f, 0xa6, 0xb8, 0xb8, 0x20, 0x3f, 0xaf, 0x38,
	0x15, 0x24, 0x9f, 0x2c, 0xc1, 0x0c, 0x91, 0x4f, 0x36, 0xba, 0xca, 0xc8, 0xc5, 0xed, 0x9b, 0x58,
	0x92, 0x11, 0x9c, 0x5a, 0x54, 0x96, 0x99, 0x9c, 0x2a, 0x64, 0xc0, 0xc5, 0xec, 0x98, 0x92, 0x22,
	0x24, 0xac, 0x07, 0xb2, 0x4a, 0x0f, 0xc5, 0x1e, 0x29, 0x11, 0x54, 0x41, 0xa8, 0x79, 0x06, 0x5c,
	0xcc, 0xc1, 0xa5, 0x49, 0x24, 0xea, 0xf0, 0x2d, 0xcd, 0x21, 0x51, 0x87, 0x4b, 0x66, 0x19, 0x09,
	0x3a, 0x9c, 0x38, 0xa3, 0xd8, 0xf5, 0xf4, 0xc1, 0xa1, 0x96, 0xc4, 0x06, 0xa6, 0x8c, 0x01, 0x01,
	0x00, 0x00, 0xff, 0xff, 0xe4, 0x92, 0x3b, 0xa6, 0x4f, 0x01, 0x00, 0x00,
}
